#' Convert a PubMed bibliography export to BibTeX
#'
#' Reads a PubMed bibliography file, creates citation labels of the form
#' `<first-author-last-name><year><first-word-of-title>`, retains commonly
#' used bibliographic fields, renames fields to match BibTeX conventions, and
#' writes the result to a BibTeX (`.bib`) file.
#'
#' Citation labels are generated by concatenating:
#' \itemize{
#'   \item the first author's last name (lowercase),
#'   \item the publication year, and
#'   \item the first word of the article title (lowercase).
#' }
#'
#' @param input Character string giving the path to the input bibliography file.
#'   The file must be readable by `revtools::read_bibliography()`.
#' @param output Character string giving the path to the output BibTeX (`.bib`)
#'   file.
#'
#' @return Invisibly returns `NULL`. A BibTeX file is written to `output`.
#'
#' @examples
#' \dontrun{
#' convert_pubmed_to_bib(
#'   input = "pubmed_results.nbib",
#'   output = "references.bib"
#' )
#' }
#'
#' @importFrom dplyr all_of rename select
#' @importFrom purrr map_chr
#' @importFrom revtools read_bibliography write_bibliography
#' @export

convert_pubmed_to_bib <- function(input, output) {
  citations <- revtools::read_bibliography(input)

  # Retrieve first word from a string
  get_first_word <- function(x) {
    purrr::map_chr(x, ~ tolower(strsplit(.x, " ")[[1]][1]))
  }

  # fmt: skip
  variables <- c(
    "label", "author", "title", 
    "journal", "year", "volume", 
    "issue", "doi", "pubmed_id"
  )

  last_names <- get_first_word(citations$author)

  first_titles <- get_first_word(citations$title)

  citations$label <- paste0(last_names, year, first_titles)

  citations <- citations |>
    dplyr::select(dplyr::all_of(variables)) |>
    dplyr::rename(
      number = issue,
      pmid = pubmed_id,
    )
  revtools::write_bibliography(citations, filename = output, format = "bib")
}
